### ISSUE TITLE
"Spring 依赖注入与 bean管理概述" 文章丢失？

### ISSUE THREAD

**Issue by ForrestLyu** [waylau/spring-boot-tutorial#3]
![snip20170902_23](https://user-images.githubusercontent.com/29992491/29991610-e5cfc7ac-8fbc-11e7-9d75-9476ee48c870.png)

**Comment by ForrestLyu** [comment]
无法点击查看 🍡

**Comment by waylau** [comment]
@ForrestLyu   还没有全部完成。欢迎补充~
